id: I58A6EC82
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:24:21+00:00'
last_modified: '2022-06-07T15:20:41.030549+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22165
  title: ཆོས་བཤད་གཞན་ཕན་ཉི་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8040':
      image_group_id: I5669
      title: ''
      total_pages: 200
      order: 1
      base_file: 8040.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
