id: P001840
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22165
  title: ཆོས་བཤད་གཞན་ཕན་ཉི་མ
  author: ''
  volumes:
    de05e2c9796e41efb033bf862056d38b:
      image_group_id: I5669
      title: ''
      volume_number: 1
      total_pages: 200
      base_file: v001.txt
